Hi,
I was not able to import matplotlib. I emailed TAs, went to office hours, and no one could figure out what
was the problem. Therefore, I was not able to do those functions. An error appears in stage 4 where the expected
value and got value are the same ,but still gives an error. An AssertionError appears in which_delimiter. 

Merry Christmas:)